export class CustPersonalContactPersonObj {
    CustPersonalContactPersonId: any;
    CustId: any;
    ContactPersonName: any;
    MrIdTypeCode: any;
    IdNo: any;
    BirthPlace: any;
    BirthDt: any;
    MotherMaidenName: any;
    MrGenderCode: any;
    MrReligionCode: any;
    IdExpiredDt : any;
    TaxIdNo : any;
    MrEducationCode: any;
    MrJobProfessionCode: any;
    MrMaritalStatCode: any;
    MrNationalityCode: any;
    NationalityCountryCode: any;
    MrCustRelationshipCode: any;
    IsEmergencyContact: any;
    IsFamily: any;
    MobilePhnNo1: any;
    MobilePhnNo2: any;
    Email: any;
    Addr: any;
    AreaCode1: any;
    AreaCode2: any;
    AreaCode3: any;
    AreaCode4: any;
    City: any;
    SubZipcode: any;
    Zipcode : any;
    ContactPersonCustNo: any;
    RowVersion: any;
}
