export class ProspectObj {
  CustName: string;
  KtpNo: string;
  BirthPlace: string;
  BirthDt: Date;
  MotherMaidenName: string;
  PhoneNo: string;
  MblPhoneNo: string;
  Addr: string;
  Rt: string;
  Rw: string;
  Zipcode: string;
  Kelurahan: string;
  Kecamatan: string;
  City: string;
  Province: string;
  RefOfficeId: number;
  CustType: string;
  AssetPriceAmt: number;
  DownPaymentAmt: number;
  NtfAmt: number;
  Tenor: number;
  InsAmt: number;
  FlatRatePrcnt: number;
  AppStep: string;
  IsActive: string;
  NoOfDependents: number;
  OfficeCode: string;
  SupplBranchEmpCode: string;
  assetTypeCode: string;
  assetHierarchyL1Code : string;
  assetHierarchyL2Code : string;
  assetCode : string;
  ProspectNo : string;
  LeadStat : string;
  LobCode : string;
  MrIdType : string;
  IdNo : string;
  MrGender : string;
  PhnArea1 : string;
  PhnArea2 : string;
  FaxArea : string;
  Fax : string;
  Npwp : string;
  EMail1 : string;
  Phn2 : string;
}
