export {BankComponent} from '../bank/bank.component';
export {EmployeeAddComponent} from '../employee/employee-add/employee-add.component';
export{SelfCustomContainerNewCustHeaderComponent} from "app/customer/sharing-component/self-custom-container-new-cust-header/self-custom-container-new-cust-header.component";
export{ThirdPartyFormComponent} from "app/customer/sharing-component/new-cust-component/component/third-party-form/third-party-form.component";
export{SelfCustomContainerThirdPartyFormComponent} from "app/customer/sharing-component/self-custom-container-third-party-form/self-custom-container-third-party-form.component";
export{SelfCustomContainerCustAttrComponent} from "app/customer/sharing-component/self-custom-container-cust-attr/self-custom-container-cust-attr.component";
export{SelfCustomCustomerPersonalAddressComponent} from "app/customer/customer-personal/self-custom-customer-personal/self-custom-customer-personal-address/self-custom-customer-personal-address.component";
export{SelfCustomContainerViewVendorAttrComponent} from "app/view/vendor/self-custom-container-view-vendor-attr/self-custom-container-view-vendor-attr.component";
export{SelfCustomContainerCustViewDocComponent} from "app/view/self-custom-cust-view/self-custom-container-cust-view-doc/self-custom-container-cust-view-doc.component";
export{SelfCustomContainerCustViewFinDataAttrComponent} from "app/view/self-custom-cust-view/self-custom-container-cust-view-fin-data-attr/self-custom-container-cust-view-fin-data-attr.component";
export{CustomerViewAsliRiComponent} from 'app/view/customer-view/customer-view-asli-ri/customer-view-asli-ri.component';
export{ CustomerViewCbasSlikComponent } from 'app/view/customer-view/customer-view-cbas-slik/customer-view-cbas-slik.component';
export{SelfCustomCustomerViewIframeGenericComponent} from "app/view/self-custom-cust-view/self-custom-customer-view-iframe-generic/self-custom-customer-view-iframe-generic.component";
export{SelfCustomContainerCustViewFinDataBankStmntComponent} from "app/view/self-custom-cust-view/self-custom-container-cust-view-fin-data-bank-stmnt/self-custom-container-cust-view-fin-data-bank-stmnt.component";
export{SelfCustomCustExposureViewComponent} from "app/view/self-custom-cust-view/self-custom-cust-exposure-view/self-custom-cust-exposure-view.component";
export{SelfCustomContainerViewExposureBucketComponent} from "app/view/self-custom-cust-view/self-custom-container-view-exposure-bucket/self-custom-container-view-exposure-bucket.component";
export{SelfCustomContainerDmsIframeComponent} from "app/shared/self-custom-container-dms-iframe/self-custom-container-dms-iframe.component";
export { SelfCustomContainerCustAttrSectionComponent } from 'app/customer/self-custom-container-cust-attr-section/self-custom-container-cust-attr-section.component';
