export class CommonConstantX {

    //Vendor Attr Code
    public static VENDOR_ATTR_CODE_SUPPLIER_TYPE = "SUPPLIER_TYPE";

    //Vendor Attr Content
    public static VENDOR_ATTR_CONT_SUPPL_TYPE_GENERAL = "GENERAL";
    public static VENDOR_ATTR_CONT_SUPPL_TYPE_FACTORING = "FACTORING";
    public static VENDOR_ATTR_CONT_SUPPL_TYPE_DEALER_FINANCING = "DEALER FINANCING";

    //Approval
    public static SCHM_CODE_VENDOR_GRD_SUPPL_BRC_SCHM_FCTR = "VENDOR_GRD_SUPPL_BRC_SCHM_FCTR";
    public static SCHM_CODE_VENDOR_GRD_SUPPL_BRC_SCHM_DLFN = "VENDOR_GRD_SUPPL_BRC_SCHM_DLFN";
    public static SCHM_CODE_VENDOR_GRD_SUPPL_BRC_SCHM = "VENDOR_GRD_SUPPL_BRC_SCHM";

    //REF OFFICE X
    public static VENDOR_VERIF_APV_TYPE = "VENDOR_VERIF_APV_TYPE_BY_X";
    public static CAT_CODE_VENDOR_VERIF_APV = "VENDOR_VERIF_APV_BY_X";
    public static SCHM_CODE_VENDOR_VERIF_APV_SCHM = "VENDOR_VERIF_APV_SCHM_BY_X";
    public static REASON_TYPE_VENDOR_VERIF_APVM = "VENDOR_VERIF_APV";
}
